name: Build and Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 17 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
      - name: Cache Maven artifacts
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache node
        uses: actions/cache@v4
        with:
          path: web-bundle/node
          key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os}}-node-
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: web-bundle/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml', '**/package.json') }}
          restore-keys: |
            ${{ runner.os}}-node_modules-
      - name: Build ${{ matrix.java-version }}
        run: mvn -B -pl core -am clean test
      - name: Run Mutation Test
        run: mvn -pl core -B pitest:mutationCoverage
      - name: Extract Mutation Score
        id: mutation
        run: |
          SCORE=$(grep -oP '(?<=<td>)[0-9]+(?=%)' core/target/pit-reports/*/index.html | sed -n '3p')
          echo "score=$SCORE" >> $GITHUB_OUTPUT
          echo "Mutation Score: $SCORE"
      - name: Compare Mutation Score with Baseline
        id: compare
        run: |
          PREVIOUS=$(cat .github/baseline_mutation.txt)
          CURRENT=${{ steps.mutation.outputs.score }}
          echo "Previous score: $PREVIOUS"
          echo "Current score: $CURRENT"

          if [ "$CURRENT" -lt "$PREVIOUS" ]; then
            echo "Baisse score de mutation"
            exit 1
          else
            echo "Score mutation plus grand ou egal baseline"
          fi